# Generated by Django 2.0.1 on 2018-04-14 10:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('tag', models.SlugField()),
                ('description', models.TextField(default='')),
                ('date', models.DateTimeField(default=datetime.datetime(2018, 4, 14, 15, 30, 59, 388665))),
                ('contact', models.EmailField(default='abc@gmail.com', max_length=254)),
                ('organiser', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
