# Generated by Django 2.0.3 on 2018-04-14 17:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logins', '0007_auto_20180414_2244'),
        ('events', '0006_auto_20180414_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(blank=True, to='logins.SignupData'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 14, 22, 44, 10, 645930)),
        ),
    ]
