# Generated by Django 2.0.3 on 2018-04-15 09:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_auto_20180415_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='club',
            field=models.CharField(choices=[('swa', 'Swayam'), ('eco', 'Eco Club'), ('art', 'Arts club'), ('abh', 'Abhinay'), ('thm', 'Theme Ballet'), ('vtk', 'Vasavi talkies'), ('csi', 'CSI')], max_length=12),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 15, 14, 41, 16, 239955)),
        ),
    ]
