# Generated by Django 2.0.3 on 2018-04-15 09:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_auto_20180415_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='club',
            field=models.CharField(choices=[('swa', 'Swayam'), ('eco', 'Eco Club'), ('art', 'Arts club'), ('tst', 'Toast Masters'), ('ora', 'Readers Club'), ('abh', 'Abhinay'), ('thm', 'Theme Ballet'), ('vtk', 'Vasavi talkies'), ('csi', 'CSI')], max_length=12),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 15, 14, 44, 9, 147037)),
        ),
    ]
