# Generated by Django 2.0.3 on 2018-04-15 09:44

import datetime
from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_auto_20180415_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 15, 15, 14, 0, 617926)),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=events.models.upload_location, width_field='width_field'),
        ),
    ]
