# Generated by Django 2.0.3 on 2018-04-15 10:50

import datetime
from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_auto_20180415_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 15, 16, 20, 23, 687341)),
        ),
        migrations.AlterField(
            model_name='event',
            name='height_field',
            field=models.IntegerField(default=300),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=events.models.upload_location, width_field='width_field'),
        ),
        migrations.AlterField(
            model_name='event',
            name='width_field',
            field=models.IntegerField(default=600),
        ),
    ]
