# Generated by Django 2.0.1 on 2018-04-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=500)),
                ('question_id_of_answer', models.IntegerField(default=0)),
                ('answer_pub_date', models.DateTimeField(default='0', verbose_name='date published')),
                ('answered_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=300)),
                ('question_pub_date', models.DateTimeField(default='0', verbose_name='date published')),
                ('asked_by', models.CharField(max_length=100)),
            ],
        ),
    ]
