# Generated by Django 2.0.3 on 2018-04-14 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logins', '0002_auto_20180414_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupdata',
            name='phone_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
