# Generated by Django 2.0.3 on 2018-04-14 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20180414_2142'),
        ('logins', '0003_auto_20180414_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupdata',
            name='events_related',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
        ),
        migrations.AlterField(
            model_name='signupdata',
            name='user_type',
            field=models.CharField(choices=[('part', 'Participant'), ('org', 'Organiser'), ('def', 'Default')], default='part', max_length=12),
        ),
    ]
