# Generated by Django 2.0.3 on 2018-04-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logins', '0004_auto_20180414_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupdata',
            name='user_type',
            field=models.CharField(choices=[('part', 'Participant'), ('org', 'Organiser'), ('def', 'Default')], default='def', max_length=12),
        ),
    ]
