# Generated by Django 2.0.3 on 2018-04-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20180414_2237'),
        ('logins', '0005_auto_20180414_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signupdata',
            name='events_related',
        ),
        migrations.AddField(
            model_name='signupdata',
            name='events_related',
            field=models.ManyToManyField(blank=True, null=True, to='events.Event'),
        ),
    ]
