# Generated by Django 2.0.3 on 2018-04-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logins', '0006_auto_20180414_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupdata',
            name='events_related',
            field=models.ManyToManyField(blank=True, to='events.Event'),
        ),
    ]
