# Generated by Django 2.0.3 on 2018-04-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logins', '0008_remove_signupdata_events_related'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signupdata',
            name='phone_num',
        ),
        migrations.AddField(
            model_name='signupdata',
            name='email',
            field=models.EmailField(blank=True, default='abc@example.com', max_length=254, null=True),
        ),
    ]
